# Generated by Django 5.0.1 on 2025-09-04 18:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='dashboard_users', related_query_name='dashboard_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='dashboard_users', related_query_name='dashboard_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OperationalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_operativo', models.CharField(blank=True, max_length=100, null=True)),
                ('id_procedimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('fuerza_interviniente', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad_interviniente', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_intervencion', models.CharField(blank=True, max_length=200, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('departamento_o_partido', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('fecha', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_iso', models.DateField(blank=True, db_index=True, null=True)),
                ('hora', models.CharField(blank=True, max_length=20, null=True)),
                ('zona_seguridad_fronteras', models.CharField(blank=True, max_length=100, null=True)),
                ('paso_fronterizo', models.CharField(blank=True, max_length=100, null=True)),
                ('otras_agencias_intervinientes', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('hoja', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('archivo_original', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('record_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-fecha_importacion', 'fecha_iso'],
                'indexes': [models.Index(fields=['fecha_iso'], name='dashboard_a_fecha_i_9262f5_idx'), models.Index(fields=['provincia_key'], name='dashboard_a_provinc_6ef5a6_idx'), models.Index(fields=['hoja'], name='dashboard_a_hoja_373875_idx'), models.Index(fields=['record_key'], name='dashboard_a_record__b5b6ed_idx')],
            },
        ),
    ]
