# Generated by Django 5.2.6 on 2025-09-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AggMensualDepartamento',
        ),
        migrations.DeleteModel(
            name='AggMensualProvincia',
        ),
        migrations.RemoveField(
            model_name='factprocedimientos',
            name='dim_geografia',
        ),
        migrations.RemoveField(
            model_name='factprocedimientos',
            name='dim_tiempo',
        ),
        migrations.DeleteModel(
            name='DimGeografia',
        ),
        migrations.DeleteModel(
            name='DimTiempo',
        ),
        migrations.DeleteModel(
            name='FactProcedimientos',
        ),
    ]
