# Generated by Django 5.0.1 on 2025-09-04 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggMensualDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_mes', models.CharField(db_index=True, max_length=7)),
                ('provincia_departamento_key', models.CharField(db_index=True, max_length=200)),
                ('provincia_key', models.CharField(db_index=True, max_length=100)),
                ('departamento_key', models.CharField(max_length=100)),
                ('provincia_nombre', models.CharField(max_length=100)),
                ('departamento_nombre', models.CharField(max_length=100)),
                ('total_procedimientos', models.IntegerField()),
                ('total_detenidos', models.IntegerField()),
                ('total_incautaciones', models.IntegerField()),
                ('total_vehiculos_controlados', models.IntegerField()),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('mes_nombre', models.CharField(max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dw_agg_mensual_departamento',
                'indexes': [models.Index(fields=['año_mes'], name='dw_agg_mens_año_mes_810e67_idx'), models.Index(fields=['provincia_departamento_key'], name='dw_agg_mens_provinc_8b265a_idx'), models.Index(fields=['provincia_key'], name='dw_agg_mens_provinc_d1d378_idx')],
                'unique_together': {('año_mes', 'provincia_departamento_key')},
            },
        ),
        migrations.CreateModel(
            name='AggMensualProvincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_mes', models.CharField(db_index=True, max_length=7)),
                ('provincia_key', models.CharField(db_index=True, max_length=100)),
                ('provincia_nombre', models.CharField(max_length=100)),
                ('total_procedimientos', models.IntegerField()),
                ('total_detenidos', models.IntegerField()),
                ('total_incautaciones', models.IntegerField()),
                ('total_vehiculos_controlados', models.IntegerField()),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('mes_nombre', models.CharField(max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dw_agg_mensual_provincia',
                'indexes': [models.Index(fields=['año_mes'], name='dw_agg_mens_año_mes_f8ea87_idx'), models.Index(fields=['provincia_key'], name='dw_agg_mens_provinc_743def_idx')],
                'unique_together': {('año_mes', 'provincia_key')},
            },
        ),
        migrations.CreateModel(
            name='DimGeografia',
            fields=[
                ('geografia_key', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=100)),
                ('provincia_key', models.CharField(db_index=True, max_length=100)),
                ('departamento_o_partido', models.CharField(max_length=100)),
                ('departamento_key', models.CharField(db_index=True, max_length=100)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('es_zona_fronteriza', models.BooleanField(default=False)),
                ('zona_seguridad_fronteras', models.CharField(blank=True, max_length=100, null=True)),
                ('latitud_promedio', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('longitud_promedio', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('provincia_departamento_key', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
            options={
                'db_table': 'dw_dim_geografia',
                'indexes': [models.Index(fields=['provincia_key'], name='dw_dim_geog_provinc_795e7c_idx'), models.Index(fields=['departamento_key'], name='dw_dim_geog_departa_3d1e07_idx'), models.Index(fields=['provincia_departamento_key'], name='dw_dim_geog_provinc_ba9743_idx')],
            },
        ),
        migrations.CreateModel(
            name='DimTiempo',
            fields=[
                ('tiempo_key', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_completa', models.DateField(db_index=True, unique=True)),
                ('año', models.IntegerField(db_index=True)),
                ('mes', models.IntegerField(db_index=True)),
                ('dia', models.IntegerField()),
                ('trimestre', models.IntegerField(db_index=True)),
                ('semestre', models.IntegerField(db_index=True)),
                ('nombre_mes', models.CharField(max_length=20)),
                ('dia_semana', models.IntegerField()),
                ('nombre_dia_semana', models.CharField(max_length=20)),
                ('es_fin_semana', models.BooleanField()),
                ('es_feriado', models.BooleanField(default=False)),
                ('año_mes', models.CharField(db_index=True, max_length=7)),
                ('año_trimestre', models.CharField(db_index=True, max_length=7)),
                ('año_semestre', models.CharField(db_index=True, max_length=7)),
            ],
            options={
                'db_table': 'dw_dim_tiempo',
                'indexes': [models.Index(fields=['año', 'mes'], name='dw_dim_tiem_año_705042_idx'), models.Index(fields=['año', 'trimestre'], name='dw_dim_tiem_año_c2b655_idx')],
            },
        ),
        migrations.CreateModel(
            name='FactProcedimientos',
            fields=[
                ('fact_key', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_procedimientos', models.IntegerField(default=1)),
                ('cantidad_detenidos', models.IntegerField(default=0)),
                ('cantidad_incautaciones', models.IntegerField(default=0)),
                ('cantidad_vehiculos_controlados', models.IntegerField(default=0)),
                ('id_operativo', models.CharField(max_length=100)),
                ('id_procedimiento', models.CharField(max_length=100)),
                ('record_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('dim_geografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.dimgeografia')),
                ('dim_tiempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.dimtiempo')),
            ],
            options={
                'db_table': 'dw_fact_procedimientos',
                'indexes': [models.Index(fields=['dim_tiempo', 'dim_geografia'], name='dw_fact_pro_dim_tie_779ca0_idx'), models.Index(fields=['id_operativo'], name='dw_fact_pro_id_oper_978e34_idx'), models.Index(fields=['record_key'], name='dw_fact_pro_record__598c9b_idx')],
            },
        ),
    ]
