# Generated by Django 5.0.1 on 2025-09-11 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0002_delete_aggmensualdepartamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_regional', models.CharField(db_index=True, max_length=10, unique=True)),
                ('nombre_regional', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dim_regionales',
                'ordering': ['codigo_regional'],
            },
        ),
        migrations.CreateModel(
            name='TipoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_operativo', models.IntegerField(db_index=True, unique=True)),
                ('nombre_operativo', models.CharField(max_length=200)),
                ('alcance', models.TextField()),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dim_tipos_operativo',
                'ordering': ['codigo_operativo'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('regional_codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('unidad_codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('total_procedimientos', models.IntegerField(default=0)),
                ('total_detenidos', models.IntegerField(default=0)),
                ('total_incautaciones', models.IntegerField(default=0)),
                ('total_controlados', models.IntegerField(default=0)),
                ('total_abatidos', models.IntegerField(default=0)),
                ('total_trata', models.IntegerField(default=0)),
                ('total_otros_delitos', models.IntegerField(default=0)),
                ('total_efectivos', models.IntegerField(default=0)),
                ('total_vehiculos', models.IntegerField(default=0)),
                ('valor_incautaciones', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'view_estadisticas_operativas',
                'indexes': [models.Index(fields=['fecha'], name='view_estadi_fecha_95492a_idx'), models.Index(fields=['regional_codigo'], name='view_estadi_regiona_f67012_idx'), models.Index(fields=['provincia'], name='view_estadi_provinc_f98673_idx')],
                'unique_together': {('fecha', 'regional_codigo', 'unidad_codigo')},
            },
        ),
        migrations.CreateModel(
            name='RankingProblematicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('anual', 'Anual')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('regional_codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('rank_detenidos', models.IntegerField(null=True)),
                ('rank_incautaciones', models.IntegerField(null=True)),
                ('rank_trata', models.IntegerField(null=True)),
                ('rank_abatidos', models.IntegerField(null=True)),
                ('count_detenidos', models.IntegerField(default=0)),
                ('count_incautaciones', models.IntegerField(default=0)),
                ('count_trata', models.IntegerField(default=0)),
                ('count_abatidos', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'view_ranking_problematicas',
                'unique_together': {('periodo', 'fecha_inicio', 'regional_codigo')},
            },
        ),
        migrations.CreateModel(
            name='TipoDelito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('detencion', 'Detención/Aprehensión'), ('incautacion', 'Incautación'), ('trata', 'Trata/Tráfico de Personas'), ('abatido', 'Abatido en Enfrentamiento'), ('otros', 'Otros Delitos'), ('evento', 'Otros Eventos')], db_index=True, max_length=20)),
                ('subcategoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('gravedad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave'), ('muy_grave', 'Muy Grave')], default='moderada', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dim_tipos_delito',
                'ordering': ['categoria', 'subcategoria'],
                'unique_together': {('categoria', 'subcategoria')},
            },
        ),
        migrations.CreateModel(
            name='UnidadOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unidad', models.CharField(db_index=True, max_length=10, unique=True)),
                ('nombre_unidad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('departamento_partido_comuna', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='dashboard_api.regional')),
            ],
            options={
                'db_table': 'dim_unidades_operativas',
                'ordering': ['regional__codigo_regional', 'codigo_unidad'],
                'indexes': [models.Index(fields=['codigo_unidad'], name='dim_unidade_codigo__c313f8_idx'), models.Index(fields=['provincia'], name='dim_unidade_provinc_986ac2_idx')],
            },
        ),
    ]
